osx_image: xcode8
language: objective-c

cache:
  directories:
  - Carthage

before_install:
- travis_wait 35; carthage bootstrap

script:
- xcodebuild clean build -project Cache.xcodeproj -scheme "Cache-Mac" -sdk macosx | xcpretty
- xcodebuild test -project Cache.xcodeproj -scheme "Cache-Mac" -sdk macosx | xcpretty
- xcodebuild clean build -project Cache.xcodeproj -scheme "Cache-iOS" -sdk iphonesimulator | xcpretty
- xcodebuild test -project Cache.xcodeproj -scheme "Cache-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
- xcodebuild clean build -project Cache.xcodeproj -scheme "Cache-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' | xcpretty
- xcodebuild test -project Cache.xcodeproj -scheme "Cache-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' | xcpretty && exit ${PIPESTATUS[0]}

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
